### ISSUE TITLE
Add alternate URL field to luggage_news

### ISSUE THREAD

**Issue by agreazel** [isubit/luggage_news#5]
Add "Alternate URL" field to the "News" content type

> Create new field
> - title: Alternate URL
> - machine name: "field: news_alternate_url"
>   Reorder so "alternate url" appears after News Types

News view for all displays:
make content fields vs. display suite
Add field: path - exclude from display, hide rewriting if empty
Add field: Alternate URL (news content type) - exclude from display, URL, as link, No results behavior add "[path]"
Make sure to change the order of the fields so that Path and Alternate URL are listed first respectively
Edit "Title" field - uncheck "Link this field to the original piece of content", Under rewrite results check "Output this field as a link", Add link path "[field_news_alternate_url]"

**Comment by jrearick** [comment]
This has been implemented. Thanks!
